Update jekyll-gh-page.yml

diff --git a/.github/workflows/jekyll-gh-page.yml b/.github/workflows/jekyll-gh-page.yml
--- a/.github/workflows/jekyll-gh-page.yml
+++ b/.github/workflows/jekyll-gh-page.yml
@@ -34,6 +34,12 @@ jobs:
         with:
           source: ./
           destination: ./_site
+      - name: Verify _site directory exists
+        run: |
+          if [ ! -d "_site" ]; then
+            echo "Error: _site directory not found."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
